adminPassword: "admin"
persistence:
  enabled: true
  size: 5Gi
service:
  type: LoadBalancer
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/default